DigitalNomads/Controllers/MapController.cs
using DigitalNomads.Data;
using DigitalNomads.Entities;
using DigitalNomads.Models.Account;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace DigitalNomads.Controllers
{
    public class MapController : Controller
    {
        private readonly CtrlAltDefeatDbContext _context;

        private readonly IHttpContextAccessor _httpContextAccessor;

        //public MapController(CtrlAltDefeatDbContext context, IHttpContextAccessor httpContextAccessor)
        //{
        //    _context = context;
        //    _httpContextAccessor = httpContextAccessor;
        //}

        //public async Task<int> GetAccountIdByUserIdAsync(string UserId)
        //{
        //    AccountGetDetailsRes res = await _context.Accounts
        //        .Where(a => a.UserId == UserId)
        //        .Select(a => new AccountGetDetailsRes
        //        {
        //            Id = a.Id,
        //            FirstName = a.FirstName,
        //            LastName = a.LastName,
        //            Lat = a.Lat,
        //            Long = a.Long,
        //            TeamId = a.TeamId

        //        }).FirstOrDefaultAsync();

        //    return res.Id;
        //}

        public async Task<IActionResult> MapAsync()
        {
            //List<Place> places = _context.Places.ToList();
            //List<Account> accounts = _context.Accounts.ToList();

            //string markeriLokacija = "[";
            //int vel = 0;
            //foreach (Place place in places)
            //{
            //    markeriLokacija += "{";
            //    double lat = place.Lat;
            //    double lng = place.Long;
            //    markeriLokacija += String.Format("'lat': '{0}',", lat.ToString(System.Globalization.CultureInfo.InvariantCulture));
            //    markeriLokacija += String.Format("'long': '{0}',", lng.ToString(System.Globalization.CultureInfo.InvariantCulture));
            //    markeriLokacija += string.Format("'name': '{0}',", place.Name.Substring(0, place.Name.Length-3));
            //    markeriLokacija += string.Format("'address': '{0}',", place.Address);
            //    markeriLokacija += string.Format("'begin': '{0}',", place.Start.Hour);
            //    markeriLokacija += string.Format("'end': '{0}',", place.End.Hour);
            //    markeriLokacija += string.Format("'speed': '{0}'", place.Name.Substring(place.Name.Length-3, 3));
            //    if (vel < places.Count - 1)
            //    {
            //        markeriLokacija += "},";
            //    }
            //    else
            //    {
            //        markeriLokacija += "}";
            //    }
            //    vel++;
            //}
            //markeriLokacija += "];";
            //ViewBag.MarkeriLokacija = markeriLokacija;

            //ViewBag.Latitude = places.ElementAt(0).Lat.ToString(System.Globalization.CultureInfo.InvariantCulture);
            //ViewBag.Longitude = places.ElementAt(0).Long.ToString(System.Globalization.CultureInfo.InvariantCulture);

            //var userId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            //int accountId = await GetAccountIdByUserIdAsync(userId);

            //int teamId = 0;


            //foreach (Account account in accounts)
            //{
            //    if (account.Id.Equals(accountId))
            //    {
            //        teamId = account.TeamId;
            //        break;
            //    }
            //}

            //string markeriTima = "[";
            //vel = 0;
            //int brojac = 0;

            //foreach (Account account in accounts)
            //{
            //    if (account.TeamId == teamId && account.UserId != userId)
            //    {
            //        brojac++;
            //    }
            //}

            //foreach (Account account in accounts)
            //{
            //    if (account.TeamId == teamId && account.UserId != userId)
            //    {
            //        markeriTima += "{";
            //        double lat = account.Lat;
            //        double lng = account.Long;
            //        markeriTima += String.Format("'lat': '{0}',", lat.ToString(System.Globalization.CultureInfo.InvariantCulture));
            //        markeriTima += String.Format("'long': '{0}',", lng.ToString(System.Globalization.CultureInfo.InvariantCulture));
            //        markeriTima += string.Format("'firstname': '{0}',", account.FirstName);
            //        markeriTima += string.Format("'lastname': '{0}'", account.LastName);

            //        if (vel < brojac - 1)
            //        {
            //            markeriTima += "},";
            //        }
            //        else
            //        {
            //            markeriTima += "}";
            //        }
            //        vel++;
            //    }
            //}

            //markeriTima += "];";
            //ViewBag.MarkeriTima = markeriTima;

            return View();
        }

       // [HttpPost]
        //public async Task<IActionResult> AddLocation(string name, string address, DateTime start, DateTime end, string speed, String addressLat, String addressLong)
        //{
        //    Place newPlace = new Place();
        //    newPlace.Name = name + speed;
        //    newPlace.Address = address;
        //    newPlace.Start = start;
        //    newPlace.End = end;
        //    newPlace.Lat = Double.Parse(addressLat, CultureInfo.InvariantCulture);
        //    newPlace.Long = Double.Parse(addressLong, CultureInfo.InvariantCulture);

        //    _context.Add(newPlace);
        //    _context.SaveChanges();

        //    return RedirectToAction("Map");

        //}
    }
}

DigitalNomads/Controllers/MeditationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DigitalNomads.Data;
using DigitalNomads.Models.Meditation;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace DigitalNomads.Controllers
{
    public class MeditationController : Controller
    {
        // GET: /<controller>/
        public IActionResult MeditationTime()
        {
            return View();
        }

        private CtrlAltDefeatDbContext _dbContext;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public MeditationController(CtrlAltDefeatDbContext dbContext, IHttpContextAccessor httpContextAccessor)
        {
            this._dbContext = dbContext;
            this._httpContextAccessor = httpContextAccessor;
        }

        public async Task<IList<MeditationRes>> GetAllMeditationDetailsAsync()
        {
            IList<MeditationRes> res = await _dbContext.Meditations
                .Select(m => new MeditationRes
                {
                    Sound = m.Sound,
                    BackgroundURL = m.BackgroundURL
                }).ToListAsync();

            return res;
        }



        public async Task<IActionResult> OneMinuteMeditation()
        {
            IList<MeditationRes> res = await GetAllMeditationDetailsAsync();
            Random rnd = new Random();
            int index = rnd.Next(res.Count);
            MeditationRes meditationRes = res[index];
            MeditationAndDurationModel model = new MeditationAndDurationModel
            {
                MeditationRes = meditationRes,
                Seconds = 60
            };
            return View("MeditationRoom", model);
        }

        public async Task<IActionResult> FiveMinutesMeditation()
        {
            IList<MeditationRes> res = await GetAllMeditationDetailsAsync();
            Random rnd = new Random();
            int index = rnd.Next(res.Count);
            MeditationRes meditationRes = res[index];
            MeditationAndDurationModel model = new MeditationAndDurationModel
            {
                MeditationRes = meditationRes,
                Seconds = 300
            };
            return View("MeditationRoom", model);
        }

        public async Task<IActionResult> TenMinutesMeditation()
        {
            IList<MeditationRes> res = await GetAllMeditationDetailsAsync();
            Random rnd = new Random();
            int index = rnd.Next(res.Count);
            MeditationRes meditationRes = res[index];
            MeditationAndDurationModel model = new MeditationAndDurationModel
            {
                MeditationRes = meditationRes,
                Seconds = 600
            };
            return View("MeditationRoom",model);
        }






    }
}

DigitalNomads/Controllers/ShowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace DigitalNomads.Controllers
{
    public class ShowController : Controller
    {
        public IActionResult ShowCards()
        {
            return View();
        }
        
    }
}

DigitalNomads/Controllers/TaskController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using DigitalNomads.Data;
using DigitalNomads.Models.Task;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
using DigitalNomads.Models.Account;
using DigitalNomads.Entities;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System;

namespace DigitalNomads.Controllers
{
    public class TaskController : Controller
    {
        private CtrlAltDefeatDbContext _dbContext;
        private readonly IHttpContextAccessor _httpContextAccessor;
  
        public TaskController(CtrlAltDefeatDbContext dbContext, IHttpContextAccessor httpContextAccessor)
        {
            this._dbContext = dbContext;
            this._httpContextAccessor = httpContextAccessor;
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}

        public async Task<IActionResult> AllTasks()
        {
            TaskList lists = await GetAllTasksByIdAsync();

            return View(lists);
        }

        public async Task<int> GetAccountIdByUserIdAsync(string UserId)
        {
            AccountGetDetailsRes res = await _dbContext.Accounts
                .Where(a => a.UserId == UserId)
                .Select(a => new AccountGetDetailsRes
                {
                    Id = a.Id,
                    FirstName = a.FirstName,
                    LastName = a.LastName,
                    Lat = a.Lat,
                    Long = a.Long

                }).FirstOrDefaultAsync();

            return res.Id;
        }

        public async Task<TaskList> GetAllTasksByIdAsync ()
        {
            //var userId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            //int accId = await GetAccountIdByUserIdAsync(userId);

            //IList<TaskRes> res = await _dbContext.Tasks
            //    .Where(t => t.UserId == accId)
            //    .Select(t => new TaskRes
            //    {
            //        Id = t.Id,
            //        Title = t.Title,
            //        IsFinished = t.IsFinished,
            //        Deadline = t.Deadline,
            //        Description = t.Description,
            //        UserId = t.UserId
            //    }).ToListAsync();

            IList<TaskRes> finished = await GetAllFinishedTasksByIdAsync();
            IList<TaskRes> unfinished = await GetAllUnfinishedTasksByIdAsync();

            return new TaskList {
                FinishedTasks = finished,
                UnfinishedTasks = unfinished
            };
        }

        public async Task<IList<TaskRes>> GetAllFinishedTasksByIdAsync()
        {
            var userId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            int accId = await GetAccountIdByUserIdAsync(userId);

            IList<TaskRes> res = await _dbContext.Tasks
                .Where(t => t.UserId == accId && t.IsFinished == true)
                .Select(t => new TaskRes
                {
                    Id = t.Id,
                    Title = t.Title,
                    IsFinished = t.IsFinished,
                    Deadline = t.Deadline,
                    Description = t.Description,
                    UserId = t.UserId
                }).ToListAsync();

            return res;
        }

        public async Task<IList<TaskRes>> GetAllUnfinishedTasksByIdAsync()
        {
            var userId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            int accId = await GetAccountIdByUserIdAsync(userId);

            IList<TaskRes> res = await _dbContext.Tasks
                .Where(t => t.UserId == accId && t.IsFinished == false)
                .Select(t => new TaskRes
                {
                    Id = t.Id,
                    Title = t.Title,
                    IsFinished = t.IsFinished,
                    Deadline = t.Deadline,
                    Description = t.Description,
                    UserId = t.UserId
                }).ToListAsync();

            var sorted = res.OrderBy(t => t.Deadline).ToList();

            return sorted;
        }

        public async Task DeleteTaskAsync(int Id)
        {
            Duty task = await _dbContext.Tasks
                .Where(t => t.Id == Id)
                .FirstOrDefaultAsync();

            _dbContext.Tasks.Remove(task);
            await _dbContext.SaveChangesAsync();
        }

        public async Task AddTaskAsync(Task task)
        {
            _dbContext.Add(task);
            await _dbContext.SaveChangesAsync();
        }

        public async Task<IActionResult> ChangeTaskType (TaskRes task)
        {
            Duty taskDb = await _dbContext.Tasks
                .Where(t => t.Id == task.Id)
                .FirstOrDefaultAsync();


            taskDb.IsFinished = true;

            _dbContext.Tasks.Update(taskDb);
            _dbContext.SaveChanges();

            TaskList lists = await GetAllTasksByIdAsync();

            return View("AllTasks", lists);
        }

        public async Task<IActionResult> AddNewTask (string Title, string Description, DateTime DeadlineDate, DateTime DeadlineTime, int UserId)
        {
            DateTime deadline = new DateTime(DeadlineDate.Year, DeadlineDate.Month, DeadlineDate.Day, DeadlineTime.Hour, DeadlineTime.Minute, DeadlineTime.Second);
            Duty newTask = new Duty();
            newTask.Title = Title;
            newTask.IsFinished = false;
            newTask.Deadline = deadline;
            newTask.Description = Description;
            newTask.UserId = UserId;

            _dbContext.Add(newTask);
            _dbContext.SaveChanges();

            TaskList lists = await GetAllTasksByIdAsync();

            return View("AllTasks", lists);
        }

        public async Task<IActionResult> RemoveTask(TaskRes task)
        {
            Duty taskDb = await _dbContext.Tasks
                .Where(t => t.Id == task.Id)
                .FirstOrDefaultAsync();

            _dbContext.Tasks.Remove(taskDb);
            _dbContext.SaveChanges();

            TaskList lists = await GetAllTasksByIdAsync();

            return View("AllTasks", lists);
        }
    }
}

DigitalNomads/Views/Show/ShowCards.cshtml
    <style>
        body {
            
            
            background-color: #2C3D4E;
            
           
            
            
        }

        .container {
            width: 1300px;
            position: relative;
            display: flex;
            justify-content: space-between;
        }

            .container .card {
                position: relative;
                cursor: pointer;
                background-color: #2C3D4E;
                border: none;
            }

            

                .container .card .face {
                    width: 300px;
                    height: 200px;
                    transition: 0.5s;
                }

                    .container .card .face.face1 {
                        position: relative;
                        background: #2C3D4E;
                        display: flex;
                        justify-content: center;
                        align-items: center;
                        z-index: 1;
                        transform: translateY(100px);
                    }

                .container .card:hover .face.face1 {
                    background: #D74833;
                    transform: translateY(0);
                }

                .container .card .face.face1 .content {
                    opacity: 0.2;
                    transition: 0.5s;
                }

                .container .card:hover .face.face1 .content {
                    opacity: 1;
                }

                .container .card .face.face1 .content img {
                    max-width: 100px;
                }

                .container .card .face.face1 .content h3 {
                    margin: 10px 0 0;
                    padding: 0;
                    color: #fff;
                    text-align: center;
                    font-size: 1.5em;
                }

                .container .card .face.face2 {
                    position: relative;
                    background: #fff;
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    padding: 20px;
                    box-sizing: border-box;
                    box-shadow: 0 20px 50px rgba(0, 0, 0, 0.8);
                    transform: translateY(-100px);
                }

                .container .card:hover .face.face2 {
                    transform: translateY(0);
                }

                .container .card .face.face2 .content p {
                    font-family: "Comic Sans MS", cursive, sans-serif;
                    margin: 0;
                    margin-bottom: 20px;
                    padding: 0;
                }

                .container .card .face.face2 .content a {
                    
                    display: inline-block;
                    text-decoration: none;
                    font-weight: 900;
                    color: #333;
                    padding: 5px;
                    border: 1px solid #333;
                }

                    .container .card .face.face2 .content a:hover {
                        background: #333;
                        color: #fff;
                    }

        .container>a {
            text-decoration: none;
            color: black;
        }
    </style>

<body>
    <div class="container">
        <a asp-controller="Map" asp-action="Map">
            <div class="card" style="margin-left: -50px; margin-top: 150px;">
                <div class="face face1">
                    <div class="content">
                        <img src="https://cdn0.iconfinder.com/data/icons/maps-navigation-1/256/15-512.png" />
                        <h3>Places</h3>
                    </div>
                </div>
                <div class="face face2">
                    <div class="content">
                        <p>To win in the marketplace you must first win in the workplace.</p>
                        @*<a href="#">Explore More</a>*@
                    </div>
                </div>
            </div>
        </a>
        <a asp-controller="Task" asp-action="AllTasks">
            <div class="card" style="margin-top: 150px;">
                <div class="face face1">
                    <div class="content">
                        <img src="https://www.freeiconspng.com/uploads/tasks-icon-15.png" />
                        <h3>Tasks</h3>
                    </div>
                </div>
                <div class="face face2">
                    <div class="content">
                        <p>If a task is ones begun, never leave it until it's done.</p>
                        @*<a href="#">Explore More</a>*@
                    </div>
                </div>
            </div>
        </a>
        <a asp-controller="Meditation" asp-action="MeditationTime">
            <div class="card" style="margin-top: 150px;">
                <div class="face face1">
                    <div class="content">
                        <img src="https://freepngimg.com/download/meditation/7-2-meditation-transparent.png"
                             style="margin-left: 15px" />
                        <h3>Meditation</h3>
                    </div>
                </div>
                <div class="face face2">
                    <div class="content">
                        <p>
                            Briliant things can happen in calm minds. Be calm. You are
                            brilliant.
                        </p>
                        @*<a href="#">Explore More</a>*@
                    </div>
                </div>
            </div>
        </a>
        <a asp-controller="Statistics" asp-action="MeditationInfo">
            <div class="card" style="margin-top: 150px;">
                <div class="face face1">
                    <div class="content">
                        <img style="margin-left: 10px"
                             src="https://library.kissclipart.com/20181005/wqe/kissclipart-statistics-vector-png-clipart-statistics-clip-art-c72889d228d98cc8.png" />
                        <h3>Statistics</h3>
                    </div>
                </div>
                <div class="face face2">
                    <div class="content">
                        <p>
                            There are two kinds of statistics, the kind you look up and the kind
                            you make up.
                        </p>
                        @*<a href="#">Explore More</a>*@
                    </div>
                </div>
            </div>
        </a>
    </div>
</body>