DigitalNomads/Models/Statistics/MeditationInfoReq.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DigitalNomads.Models.Statistics
{
    public class MeditationInfoReq
    {
        public int HoursOfSleep { get; set; }
        public int Day { get; set; }
        public int HoursFromPreviousBreak { get; set; }
        public int CurrentMood { get; set; }
        public int HoursFromPreviousMeditation { get; set; }
    }
}

DigitalNomads/Models/Statistics/StatisticsResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DigitalNomads.Models.Statistics
{
    public class StatisticsResult
    {
        public string Message1 { get; set; }
        public string Message2 { get; set; }
    }
}

DigitalNomads/Controllers/MeditationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DigitalNomads.Data;
using DigitalNomads.Models.Meditation;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace DigitalNomads.Controllers
{
    public class MeditationController : Controller
    {
        // GET: /<controller>/
        public IActionResult MeditationTime()
        {
            return View();
        }

        private CtrlAltDefeatDbContext _dbContext;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public MeditationController(CtrlAltDefeatDbContext dbContext, IHttpContextAccessor httpContextAccessor)
        {
            this._dbContext = dbContext;
            this._httpContextAccessor = httpContextAccessor;
        }

        public async Task<IList<MeditationRes>> GetAllMeditationDetailsAsync()
        {
            IList<MeditationRes> res = await _dbContext.Meditations
                .Select(m => new MeditationRes
                {
                    Sound = m.Sound,
                    BackgroundURL = m.BackgroundURL
                }).ToListAsync();

            return res;
        }



        public async Task<IActionResult> OneMinuteMeditation()
        {
            IList<MeditationRes> res = await GetAllMeditationDetailsAsync();
            Random rnd = new Random();
            int index = rnd.Next(res.Count);
            MeditationRes meditationRes = res[index];
            MeditationAndDurationModel model = new MeditationAndDurationModel
            {
                MeditationRes = meditationRes,
                Seconds = 60
            };
            return View("MeditationRoom", model);
        }

        public async Task<IActionResult> FiveMinutesMeditation()
        {
            IList<MeditationRes> res = await GetAllMeditationDetailsAsync();
            Random rnd = new Random();
            int index = rnd.Next(res.Count);
            MeditationRes meditationRes = res[index];
            MeditationAndDurationModel model = new MeditationAndDurationModel
            {
                MeditationRes = meditationRes,
                Seconds = 300
            };
            return View("MeditationRoom", model);
        }

        public async Task<IActionResult> TenMinutesMeditation()
        {
            IList<MeditationRes> res = await GetAllMeditationDetailsAsync();
            Random rnd = new Random();
            int index = rnd.Next(res.Count);
            MeditationRes meditationRes = res[index];
            MeditationAndDurationModel model = new MeditationAndDurationModel
            {
                MeditationRes = meditationRes,
                Seconds = 600
            };
            return View("MeditationRoom",model);
        }






    }
}

DigitalNomads/Controllers/ShowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace DigitalNomads.Controllers
{
    public class ShowController : Controller
    {
        public IActionResult ShowCards()
        {
            return View();
        }
        
    }
}

DigitalNomads/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;

using System.Net.Http.Headers;
using System.Runtime.ConstrainedExecution;
using System.Threading.Tasks;
using DigitalNomads.Data;
using DigitalNomads.Models.Statistics;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;


namespace DigitalNomads.Controllers
{

    public class StringTable
    {
        public string[] ColumnNames { get; set; }
        public string[,] Values { get; set; }
    }

    public class StatisticsController : Controller
    {
        // GET: /<controller>/
        public IActionResult MeditationInfo()
        {
            return View();

        }

        private CtrlAltDefeatDbContext _dbContext;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public StatisticsController(CtrlAltDefeatDbContext dbContext, IHttpContextAccessor httpContextAccessor)
        {
            this._dbContext = dbContext;
            this._httpContextAccessor = httpContextAccessor;
        }


        public async Task<IActionResult> CalculateMeditationNeed(MeditationInfoReq req)
        {
            if(req.Day == 0 || req.Day == 6)
            {
                req.Day = 1;
            }

            using (var client = new HttpClient())
            {
                var scoreRequest = new
                {

                    Inputs = new Dictionary<string, StringTable>() {
                        {
                            "input1",
                            new StringTable()
                            {
                                ColumnNames = new string[] {"Hours of sleep", "Day of week", "Hours from previous break", "Current mood", "Hours from previous meditation"},
                                Values = new string[,] {  { req.HoursOfSleep.ToString(), req.Day.ToString(), req.HoursFromPreviousBreak.ToString(), req.CurrentMood.ToString(), req.HoursFromPreviousMeditation.ToString() },  { "0", "0", "0", "0", "0" },  }
                            }
                        },
                    },
                    GlobalParameters = new Dictionary<string, string>()
                    {
                    }
                };
                const string apiKey = "gCPcBiHl3nqnXscWEu03gE0zcv7kvfAyoY5r5UyYGn+OtFDniijD1ml5bRiSDRKVrnIlR46N8J2Ouxz4yqmUIA=="; // Replace this with the API key for the web service
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);

                client.BaseAddress = new Uri("https://ussouthcentral.services.azureml.net/workspaces/dfac26d08b5740aa9f52c2ee56a84c7d/services/1183180dfa4a463389d3a532ac1e8049/execute?api-version=2.0&details=true");



                HttpResponseMessage response = await client.PostAsJsonAsync("", scoreRequest);

                if (response.IsSuccessStatusCode)
                {
                    string result = await response.Content.ReadAsStringAsync();

                    string[] splitThis = result.Split('"');
                    string finalResult = splitThis[splitThis.Length - 18];
                   

                    int statisticData = Convert.ToInt32(finalResult);
                    if(statisticData == 1)
                    {
                        StatisticsResult st = new StatisticsResult
                        {
                            Message1 = "Mental health and peaceful mind is really important.",
                            Message2 = "You should go meditate and relax yourself"
                        };
                        return View("StatisticsResult", st);
                    }
                    else
                    {
                        StatisticsResult st = new StatisticsResult
                        {
                            Message1 = "It is great to see that you worry about your mental health.",
                            Message2 = "Keep working, and come back in few hours."
                        };
                        return View("StatisticsResult", st);
                    }
                 
                        
                }
                else
                {
                    Console.WriteLine(string.Format("The request failed with status code: {0}", response.StatusCode));

                    // Print the headers - they include the requert ID and the timestamp, which are useful for debugging the failure
                    Console.WriteLine(response.Headers.ToString());

                    string responseContent = await response.Content.ReadAsStringAsync();
                    Console.WriteLine(responseContent);
                }

                return View();

                
            }
        }
    }
}

DigitalNomads/Views/Statistics/MeditationInfo.cshtml
<html>
<head>

</head>
<body style="        background-color:RGB(80, 115, 101)
">
    <div class="card-deck" style="margin-top:80px;margin-left:40px; width:90%">
        <div class="card">
            <img src="https://www.klaviyo.com/wp-content/uploads/2016/09/abstract-background-1024x273.jpg" class="card-img-top" alt="..." style="height:40%;">
            <h5 class="card-title" style="margin-top:140px;position:absolute; color:white;font-size:30px;margin-left:20px">Check if you should take a break and meditate</h5>


            <main>
                <form asp-controller="Statistics" asp-action="CalculateMeditationNeed" method="post" style="margin:auto">
                    <ul class="list-group list-group-flush" style="margin-top:30px;">
                        <li class="list-group-item">
                            How many hours did you sleep last night?
                            <input type="number" name="HoursOfSleep" style="margin-left:10px" />
                        </li>
                        <input type="hidden" id="Day" name="Day" value='@DateTime.Now.DayOfWeek' />
                        <li class="list-group-item">
                            How many hours ago did you take a break?
                            <input type="number" name="HoursFromPreviousBreak" />
                        </li>
                        <li class="list-group-item">
                            Evaluate your current mood.
                            <input type="number" name="CurrentMood" style="margin-left:110px" />
                        </li>
                        <li class="list-group-item">
                            How many hours ago did you meditate?


                            <input type="number" name="HoursFromPreviousMeditation" style="margin-left:29px" />
                        </li>
                        <li><button class="btn btn-outline-secondary" type="submit" style="margin-top:10px; margin-left:67%">Check</button></li>

                    </ul>
                </form>
            </main>
        </div>
    </div>
</body>
</html>

<style>
    ul li:hover {
        background-color: #F5F5F5;
    }

    .list-group-item {
        padding-left: 220px;
    }
</style>

DigitalNomads/Views/Statistics/StatisticsResult.cshtml
@{
}

<html>
<head>

</head>
<body >
    <div class="wrap">
        <h1>@Model.Message1</h1>
        <h3>@Model.Message2</h3>
    </div>
    <div class="btn-wrap">
        <a href="@Url.Action("MeditationTime", "Meditation")" class="btn btn-outline-light">
            click to meditate
        </a>
        <br />
        <br />
       <a  id="dr" href="@Url.Action("ShowCards", "Show")" class="btn btn-outline-light" style="margin-left:15px;">
        go back to work
        </a>
    </div>
</body>
</html>

<style>
    
   
    .btn-wrap {
        margin-top:25px;
    display:flex;
    margin-left:100px;

    }
   
    .wrap {
        max-width: 550px;
        margin-top: 160px;
        margin-left: -220px;
    }
    body {
        background-image: url(https://i.pinimg.com/originals/36/e6/d5/36e6d5428dfed2568b0a412a53841a36.jpg);
        background-repeat: no-repeat;
    }

        h1 {
            color: whitesmoke;
            margin-left: 170px;
        }

    h3 {
        padding-top: 20px;
        color: whitesmoke;
        align-items: center;
        margin-left: 170px;
    }
    


   
       
</style>